"""Combined Tianji dual-arm robot with Wuji dexterous hands.

Uses the pre-combined USD at ``assets/tianji/tianji_wuji.usd``, generated by
``scripts/tools/generate_tianji_wuji_usd.py``. No runtime stage edits needed.
"""

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

ASSET_PATH = Path(__file__).resolve().parents[4] / "assets" / "tianji"

TIANJI_WUJI_CFG = ArticulationCfg(
    prim_path="{ENV_REGEX_NS}/Robot",
    spawn=sim_utils.UsdFileCfg(
        usd_path=str(ASSET_PATH / "tianji_wuji.usd"),
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=True,
            max_depenetration_velocity=5.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=64,
            solver_velocity_iteration_count=0,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0, 0, 0),
        rot=(1, 0, 0, 0),
        joint_pos={
            # Left arm (7)
            "left_joint1": 0.0, "left_joint2": 0.0, "left_joint3": 0.0, "left_joint4": 0.0,
            "left_joint5": 0.0, "left_joint6": 0.0, "left_joint7": 0.0,
            # Right arm (7)
            "right_joint1": 0.0, "right_joint2": 0.0, "right_joint3": 0.0, "right_joint4": 0.0,
            "right_joint5": 0.0, "right_joint6": 0.0, "right_joint7": 0.0,
            # Left Wuji hand (20)
            "left_finger1_joint1": 0.5, "left_finger1_joint2": 0.3,
            "left_finger1_joint3": 0.3, "left_finger1_joint4": 0.3,
            "left_finger2_joint1": 0.3, "left_finger2_joint2": 0.0,
            "left_finger2_joint3": 0.3, "left_finger2_joint4": 0.3,
            "left_finger3_joint1": 0.3, "left_finger3_joint2": 0.0,
            "left_finger3_joint3": 0.3, "left_finger3_joint4": 0.3,
            "left_finger4_joint1": 0.3, "left_finger4_joint2": 0.0,
            "left_finger4_joint3": 0.3, "left_finger4_joint4": 0.3,
            "left_finger5_joint1": 0.3, "left_finger5_joint2": 0.0,
            "left_finger5_joint3": 0.3, "left_finger5_joint4": 0.3,
            # Right Wuji hand (20)
            "right_finger1_joint1": 0.5, "right_finger1_joint2": 0.3,
            "right_finger1_joint3": 0.3, "right_finger1_joint4": 0.3,
            "right_finger2_joint1": 0.3, "right_finger2_joint2": 0.0,
            "right_finger2_joint3": 0.3, "right_finger2_joint4": 0.3,
            "right_finger3_joint1": 0.3, "right_finger3_joint2": 0.0,
            "right_finger3_joint3": 0.3, "right_finger3_joint4": 0.3,
            "right_finger4_joint1": 0.3, "right_finger4_joint2": 0.0,
            "right_finger4_joint3": 0.3, "right_finger4_joint4": 0.3,
            "right_finger5_joint1": 0.3, "right_finger5_joint2": 0.0,
            "right_finger5_joint3": 0.3, "right_finger5_joint4": 0.3,
        },
    ),
    soft_joint_pos_limit_factor=1,
    actuators={
        # Arms — stiffness/damping from USD by default.
        # Override to 0 for OSC (effort control) in the env config, not here.
        "left_shoulder": ImplicitActuatorCfg(
            joint_names_expr=["left_joint[1-4]"], stiffness=None, damping=None,
        ),
        "left_forearm": ImplicitActuatorCfg(
            joint_names_expr=["left_joint[5-7]"], stiffness=None, damping=None,
        ),
        "right_shoulder": ImplicitActuatorCfg(
            joint_names_expr=["right_joint[1-4]"], stiffness=None, damping=None,
        ),
        "right_forearm": ImplicitActuatorCfg(
            joint_names_expr=["right_joint[5-7]"], stiffness=None, damping=None,
        ),
        # Hands — use USD defaults (position control via JointPositionAction)
        "left_thumb": ImplicitActuatorCfg(
            joint_names_expr=["left_finger1_joint[1-4]"], stiffness=None, damping=None,
        ),
        "left_fingers": ImplicitActuatorCfg(
            joint_names_expr=["left_finger[2-5]_joint[1-4]"], stiffness=None, damping=None,
        ),
        "right_thumb": ImplicitActuatorCfg(
            joint_names_expr=["right_finger1_joint[1-4]"], stiffness=None, damping=None,
        ),
        "right_fingers": ImplicitActuatorCfg(
            joint_names_expr=["right_finger[2-5]_joint[1-4]"], stiffness=None, damping=None,
        ),
    },
)
